package com.appcontrol

import com.appcontrol.data.repository.HistoryRepositoryImpl
import com.appcontrol.domain.model.HistoryEvent
import com.appcontrol.domain.model.HistoryEventType
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class HistoryRepositoryTest {

    private lateinit var dao: FakeHistoryDao
    private lateinit var repository: HistoryRepositoryImpl

    @Before
    fun setUp() {
        dao = FakeHistoryDao()
        repository = HistoryRepositoryImpl(dao)
    }

    @Test
    fun insert_incrementsAutoGeneratedId() = runBlocking {
        val id1 = repository.insert(event("first", HistoryEventType.CHECK))
        val id2 = repository.insert(event("second", HistoryEventType.ERROR))

        assertTrue(id1 > 0L)
        assertTrue(id2 > id1)
    }

    @Test
    fun getById_returnsInsertedEvent() = runBlocking {
        val id = repository.insert(event("whoami", HistoryEventType.CHECK))
        val loaded = repository.getById(id)

        assertNotNull(loaded)
        assertEquals("whoami", loaded?.title)
        assertEquals(HistoryEventType.CHECK, loaded?.eventType)
    }

    @Test
    fun getById_missing_returnsNull() = runBlocking {
        assertNull(repository.getById(999L))
    }

    @Test
    fun getAll_returnsMostRecentFirst() = runBlocking {
        repository.insert(event("old", HistoryEventType.ACTION, timestamp = 1_000L))
        repository.insert(event("new", HistoryEventType.ERROR, timestamp = 2_000L))
        repository.insert(event("middle", HistoryEventType.CHECK, timestamp = 1_500L))

        val all = repository.getAll(limit = 10)

        assertEquals(listOf("new", "middle", "old"), all.map { it.title })
    }

    @Test
    fun getByType_filtersByEventType() = runBlocking {
        repository.insert(event("c1", HistoryEventType.CHECK))
        repository.insert(event("e1", HistoryEventType.ERROR))
        repository.insert(event("c2", HistoryEventType.CHECK))

        val errors = repository.getByType(HistoryEventType.ERROR, limit = 10)
        val checks = repository.getByType(HistoryEventType.CHECK, limit = 10)

        assertEquals(listOf("e1"), errors.map { it.title })
        assertEquals(setOf("c1", "c2"), checks.map { it.title }.toSet())
    }

    @Test
    fun getByPackage_filtersByPackageName() = runBlocking {
        repository.insert(event("a", HistoryEventType.ACTION, packageName = "com.a"))
        repository.insert(event("b", HistoryEventType.ACTION, packageName = "com.b"))
        repository.insert(event("a2", HistoryEventType.ERROR, packageName = "com.a"))

        val result = repository.getByPackage("com.a", limit = 10)

        assertEquals(setOf("a", "a2"), result.map { it.title }.toSet())
        assertTrue(result.all { it.packageName == "com.a" })
    }

    @Test
    fun getByProfile_filtersByProfileId() = runBlocking {
        repository.insert(event("p1", HistoryEventType.CHECK, profileId = 7L))
        repository.insert(event("p2", HistoryEventType.CHECK, profileId = 8L))
        repository.insert(event("p1b", HistoryEventType.ERROR, profileId = 7L))

        val result = repository.getByProfile(7L, limit = 10)

        assertEquals(setOf("p1", "p1b"), result.map { it.title }.toSet())
        assertTrue(result.all { it.profileId == 7L })
    }

    @Test
    fun cleanup_removesOnlyBeforeTimestamp() = runBlocking {
        repository.insert(event("old", HistoryEventType.ACTION, timestamp = 1_000L))
        repository.insert(event("oldToo", HistoryEventType.ACTION, timestamp = 999L))
        repository.insert(event("fresh", HistoryEventType.CHECK, timestamp = 5_000L))

        val removed = repository.cleanup(beforeTimestamp = 1_000L)

        assertEquals(1, removed)
        assertEquals(listOf("fresh", "old"), getAllTitles())
    }

    @Test
    fun clearAll_removesEverything() = runBlocking {
        repository.insert(event("a", HistoryEventType.CHECK))
        repository.insert(event("b", HistoryEventType.ERROR))

        val cleared = repository.clearAll()

        assertEquals(2, cleared)
        assertTrue(dao.events.isEmpty())
    }

    private suspend fun getAllTitles(): List<String> =
        repository.getAll(limit = 10).map { it.title }

    private fun event(
        title: String,
        type: HistoryEventType,
        timestamp: Long = 1_000L,
        packageName: String? = null,
        profileId: Long? = null
    ): HistoryEvent = HistoryEvent(
        timestamp = timestamp,
        eventType = type,
        title = title,
        description = "desc for $title",
        packageName = packageName,
        profileId = profileId
    )
}